In [50]:
import pymongo
import pandas as pd

In [17]:
client = pymongo.MongoClient('mongodb://localhost:27017')

In [18]:
collection = client.movie.movies

In [57]:
mov = collection.find({"year":1994})

In [58]:
df = pd.DataFrame({'Title':[],'Year':[],'Rating':[]})
j = 0
for i in mov:
   df.loc[j] = [i['title'],i['year'],i['rating']]
   j += 1

In [59]:
df

                      Title  Year  Rating
0              Forrest Gump  1994     8.8
1  The Shawshank Redemption  1994     9.3

In [45]:
df = pd.DataFrame({'Title':[],'Year':[],'Rating':[]})

In [49]:
df

          Title  Year  Rating
0  Pulp Fiction  1994     8.9

In [48]:
df.loc[0] =['Pulp Fiction', 1994, 8.9]

In [32]:
collection.delete_one({'director':'Quentin Tarantino'})

DeleteResult({'n': 1, 'ok': 1.0}, acknowledged=True)