In [9]:
import numpy as np
import pandas as pd

In [15]:
df = pd.read_csv('seoul+bike+sharing+demand.zip', encoding='latin_1')

In [16]:
df.head()

,Date,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [17]:
df.shape

(8760, 14)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       8760 non-null   object
 1   Rented Bike Count          8760 non-null   int64
 2   Hour                       8760 non-null   int64
 3   Temperature(°C)            8760 non-null   float64
 4   Humidity(%)                8760 non-null   int64
 5   Wind speed (m/s)           8760 non-null   float64
 6   Visibility (10m)           8760 non-null   int64
 7   Dew point temperature(°C)  8760 non-null   float64
 8   Solar Radiation (MJ/m2)    8760 non-null   float64
 9   Rainfall(mm)               8760 non-null   float64
 10  Snowfall (cm)              8760 non-null   float64
 11  Seasons                    8760 non-null   object
 12  Holiday                    8760 non-null   object
 13  Functioning Day            8760 non-null   object
dtypes: float64(6), int64(4), object(4)
memory usage: 958.2+ KB

In [19]:
df.describe()

,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm)
count,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000,8760.000000
mean,704.602055,11.500000,12.882922,58.226256,1.724909,1436.825799,4.073813,0.569111,0.148687,0.075068
std,644.997468,6.922582,11.944825,20.362413,1.036300,608.298712,13.060369,0.868746,1.128193,0.436746
min,0.000000,0.000000,-17.800000,0.000000,0.000000,27.000000,-30.600000,0.000000,0.000000,0.000000
25%,191.000000,5.750000,3.500000,42.000000,0.900000,940.000000,-4.700000,0.000000,0.000000,0.000000
50%,504.500000,11.500000,13.700000,57.000000,1.500000,1698.000000,5.100000,0.010000,0.000000,0.000000
75%,1065.250000,17.250000,22.500000,74.000000,2.300000,2000.000000,14.800000,0.930000,0.000000,0.000000
max,3556.000000,23.000000,39.400000,98.000000,7.400000,2000.000000,27.200000,3.520000,35.000000,8.800000

In [22]:
df['Date'] = pd.to_datetime(df['Date'])

In [23]:
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [24]:
df = df.drop('Date',axis=1)

In [25]:
df.head()

,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day,Month,Day
0,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,1,12
1,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,1,12
2,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes,1,12
3,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes,1,12
4,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes,1,12

In [27]:
df.describe(include='object')

       Seasons     Holiday Functioning Day
count     8760        8760            8760
unique       4           2               2
top     Spring  No Holiday             Yes
freq      2208        8328            8465

In [32]:
pd.get_dummies(df['Seasons'], dtype=int, drop_first=True).head(3)

   Spring  Summer  Winter
0       0       0       1
1       0       0       1
2       0       0       1

In [31]:
df['Seasons'].head(3)

0    Winter
1    Winter
2    Winter
Name: Seasons, dtype: object

In [33]:
categorical = df.describe(include='object').columns

In [34]:
categorical

Index(['Seasons', 'Holiday', 'Functioning Day'], dtype='object')

In [35]:
for col in categorical:
  temp = pd.get_dummies(df[col], dtype=int, drop_first=True)
  df = pd.concat((df, temp), axis=1)
  df = df.drop(col, axis=1)

In [36]:
df.head()

,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Month,Day,Spring,Summer,Winter,No Holiday,Yes
0,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,1,12,0,0,1,1,1
1,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,1,12,0,0,1,1,1
2,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,1,12,0,0,1,1,1
3,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,1,12,0,0,1,1,1
4,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,1,12,0,0,1,1,1

In [37]:
X = df.drop('Rented Bike Count', axis=1)
Y = df['Rented Bike Count']

In [50]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [39]:
X_train,X_test, Y_train, Y_test = train_test_split(X,Y, test_size=.15)

In [40]:
pipe = Pipeline(
    [
        ('Scaler', StandardScaler()),
        ('LR',LinearRegression())
    ]
)

In [55]:
pipe = Pipeline(
    [
        ('Scaler', StandardScaler()),
        ('LR',SVR(kernel='rbf'))
    ]
)

In [51]:
pipe = Pipeline(
    [
        ('Scaler', StandardScaler()),
        ('LR',KNeighborsRegressor(n_neighbors=5))
    ]
)

In [56]:
pipe.fit(X_train, Y_train)

Pipeline(steps=[('Scaler', StandardScaler()), ('LR', SVR())])

In [57]:
mean_absolute_error(Y_test, pipe.predict(X_test))

362.40483311162967

In [54]:
mean_absolute_error(Y_test, pipe.predict(X_test)) / np.mean(df['Rented Bike Count'])

0.2672141004708013